# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNxlNElRsAMF5NyZCWynBj2EYZVXAw22
"""

import pandas as pd


!wget https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv -O WHO_COVID-19_cases.csv


df = pd.read_csv("WHO_COVID-19_cases.csv")


print("Dataframe ning birinchi 5 qatori:")
print(df.head())



country = "Uzbekistan"
filtered_country = df[df['Country'] == country]
print(f"\n{country} davlatiga oid ma'lumotlar:")
print(filtered_country)


date_filter = "2021-01-01"
filtered_date = df[pd.to_datetime(df['Date_reported']) > pd.to_datetime(date_filter)]
print(f"\n{date_filter} sanasidan keyingi ma'lumotlar:")
print(filtered_date.head())


filtered_cases = df[df['New_cases'] > 1000]
print("\nYuqtirish holatlari 1000 dan yuqori bo'lgan davlatlar:")
print(filtered_cases.head())


selected_columns = df[['Date_reported', 'Country', 'New_cases', 'Cumulative_cases']]
print("\nKerakli ustunlar bilan tanlangan ma'lumotlar:")
print(selected_columns.head())

import pandas as pd

!wget https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv -O WHO_COVID-19_cases.csv

df = pd.read_csv("WHO_COVID-19_cases.csv")

country_cases = df.groupby("Country")["Cumulative_cases"].max().reset_index()
country_cases_sorted = country_cases.sort_values(by="Cumulative_cases", ascending=False)

print(country_cases_sorted)

import matplotlib.pyplot as plt

top_10_countries = country_cases_sorted.head(10)
plt.figure(figsize=(10, 6))
plt.bar(top_10_countries['Country'], top_10_countries['Cumulative_cases'], color='skyblue')
plt.title("COVID-19 Holatlari Eng Ko'p Aniqlangan 10 Davlat", fontsize=14)
plt.xlabel("Davlat", fontsize=12)
plt.ylabel("Aniqlangan COVID-19 Holatlari", fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()